stages:
    - test

frontend_tests:
    stage: test
    image: node:20.18.3 
    before_script:
        - cd react  
        - npm ci  
    script:
        - npm test -- --ci --run
    artifacts:
        reports:
            junit: react/test-results-frontend.json
        expire_in: 7 days
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

backend_tests:
    stage: test
    image: node:20.18.3
    before_script:
        - cd express  
        - npm ci
    script:
        - npm test -- --ci --runInBand
    artifacts:
        reports:
            junit: express/test-results/jest-junit.xml
        expire_in: 7 days
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'