name: plant-together

services:
  plant-together-react:
    build:
      context: ./react
      args:
        VITE_SERVER_HTTP_URL: ${VITE_SERVER_HTTP_URL:-http://localhost:${PORT:-3000}}
        VITE_SERVER_WS_URL: ${VITE_SERVER_WS_URL:-ws://localhost:${YREDIS_PORT:-3003}}
        VITE_POSTHOG_KEY: ${VITE_POSTHOG_KEY:-''}
        VITE_POSTHOG_HOST: ${VITE_POSTHOG_HOST:-''}
        VITE_CLARITY_PROJECT_ID: ${VITE_CLARITY_PROJECT_ID:-''}
    container_name: plant-together-react
    restart: always
    ports:
      - ${VITE_PORT:-4173}:4173
    networks:
      - plant-together-network
      - yredis-network

  plant-together-express:
    build:
      context: ./express
    container_name: plant-together-express
    restart: always
    environment:
      - PORT=${PORT:-3000}

      # Adjust database credentials locally in .env, do not commit!
      - DB_NAME=${DB_NAME:-postgres}
      - DB_HOST=${DB_HOST:-database-psql}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-1234}
    depends_on:
      - database-psql
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    networks:
      - plant-together-network

  plant-together-yredis:
    build:
      context: ./y-redis
    container_name: plant-together-yredis
    restart: always
    environment:
      - PORT=${YREDIS_PORT:-3003}
      - LOG=${LOG:-"^(?!No tasks available).*$"}
      - REDIS=${REDIS:-redis://redis-together}
      - POSTGRES=${POSTGRES:-postgres://${DB_USER:-postgres}:${DB_PASS:-1234}@${DB_HOST:-database-psql}/${DB_NAME:-postgres}}
    depends_on:
      - database-psql
      - redis-together
    ports:
      - ${YREDIS_PORT:-3003}:${YREDIS_PORT:-3003}
    networks:
      - plant-together-network
      - yredis-network

  redis-together:
    image: redis:6.2
    container_name: redis-together
    restart: always
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - yredis-network

  database-psql:
    image: postgres:16.2
    container_name: database-psql
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata-plant-together:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${DB_PASS:-1234}
    ports:
      - ${PSQL_PORT:-5432}:5432
    networks:
      - plant-together-network

  pgadmin-together:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin-together
    restart: always
    depends_on:
      - database-psql
    volumes:
      - pgadmin-together:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL:-developer@plant-together.com}
      - PGADMIN_DEFAULT_PASSWORD=${ADMIN_PASS:-1234}
    ports:
      - ${PGADMIN_PORT:-1007}:80
    networks:
      - plant-together-network

volumes:
  pgdata-plant-together:
    name: pgdata-plant-together
    driver: local
  pgadmin-together:
    name: pgadmin-together
    driver: local

networks:
  plant-together-network:
  yredis-network:
